#include "COLOR.H"
class Colours{
  if(color==black)
  {
    Color Black (0.0,0.0,0.0,0.0);
  }
  else if (color==blue){
    Color Blue (0.0,0.0,0.5,0.0);
  }
  else if (color==cyan){
    Color Cyan (0.0,0.9,0.9,0.0);
  }
  else if (color==darkBlue){
    Color darkBlue (0.1,0,0.4,0.0);
  }
  else if (color==darkCyan){
    Color darkCyan (0.1,0.6,0.8,0.0);
  }
  else if (color==darkGray){
    Color darkGray (0.5,0.5,0.5,0.0);
  }
  else if (color==darkGreen){
    Color darkGreen (0.2,0.3,0.1,0.0);
  }
  else if (color==darkRed){
    Color darkRed (0.5,0.0,0.0,0.0);
  }
  else if (color==darkMagenta){
    Color darkMagenta (0.6,0.0,0.1,0.0);
  }
   else if (color==darkRed){
    Color darkRed (0.7,0.0,0.0,0.0);
  }
   else if (color==darkYellow){
    Color darkYellow (1.0,0.9,0.1,0.0);
  }
  else if (color==gray){
    Color gray (0.5,0.5,0.5,0.0);
  }
  else if (color==green){
    Color green (0.2,0.9,0.0,0.0);
  }
  else if (color==lightGray){
    Color lightGray (0.7,0.7,0.7,0.0);
  }
  else if (color==magenta){
    Color magenta (1.0,0.0,1.0,0.0);
  }
  else if (color==red){
    Color red (1.0,0.0,0.0,0.0);
  }
  else if (color==white){
    Color white (1.0,1.0,1.0,0.0);
  }
  else (color==yellow){
    Color yellow (1.0,1.0,0.1,0.0);
  }
}
