#include "COLOR.H"
class Colours{
  if(color==black)
  {
    Color Black (0.0,0.0,0.0,0.0);
  }
  else if (color==blue){
    Color Blue (0.0,0.0,0.5,0.0);
  }
  else if (color==cyan){
    Color Cyan (0.0,0.9,0.9,0.0);
  }
  else if (color==darkBlue){
    Color darkBlue (0.1,0,0.4,0.0);
  }
  else if (color==darkCyan){
    Color darkCyan (0.1,0.6,0.8,0.0);
  }
  else if (color==darkGray){
    Color darkGray (0.5,0.5,0.5,0.0);
  }
  else if (color==darkGreen){
    Color darkGreen (0.2,0.3,0.1,0.0);
  }
  else if (color==darkRed){
    Color darkRed (0.5,0.0,0.0,0.0);
  }
  else if (color==darkMagenta){
    Color darkMagenta (0.6,0.0,0.1,0.0);
  }
   else if (color==darkRed){
    Color darkRed (0.7,0.0,0.0,0.0);
  }
   else if (color==darkYellow){
    Color darkYellow (1.0,0.9,0.1,0.0);
  }
  else if (color==gray){
    Color gray (0.5,0.5,0.5,0.0);
  }
  else if (color==green){
    Color green (0.2,0.9,0.0,0.0);
  }
  else if (color==lightGray){
    Color lightGray (0.7,0.7,0.7,0.0);
  }
  else if (color==magenta){
    Color magenta (1.0,0.0,1.0,0.0);
  }
  else if (color==red){
    Color red (1.0,0.0,0.0,0.0);
  }
  else if (color==white){
    Color white (1.0,1.0,1.0,0.0);
  }
  else if (color==yellow){
    Color yellow (1.0,1.0,0.1,0.0);
  }
  
  //second section
     else if (color==fuchsia){

    Color fuchsia (07,0.0,0.7,0.0);
}
 

   else if (color==forestgreen){

    Color forestgreen (0.3,0.4,0.1,0.0);

}
 else if (color==ghostwhite){

    Color ghostwhite (0.9,0.9,0.9,0.0);

}
 else if (color==gainsboro){

    Color gainsboro(0.7,0.7,0.7,0.0);

}

 else if (color==gold){

    Color gold (0.9,0.9,0.3,0.0);

}

 else if (color==goldenrod){

    Color goldenrod (0.9,0.7,0.0,0.0);

}
else if (color==gray){

    Color gray (0.5,0.5,0.5,0.0);

}
else if (color==green){

    Color green (0.2,0.9,0.0,0.0);

}
else if (color==greenyellow){

    Color greenyellow (0.7,1.0,0.0,0.0);

}

else if (color==grey){

    Color grey (0.7,0.7,0.6,0.0);
}

else if (color==honeydew){

    Color honeydew (1.0,0.8,0.2,0.0);
}
else if (color==hotpink){

    Color hotpink (1.0,0.4,0.8,0.0);
}
else if (color==indianred){

    Color indianred (0.6,0.0,0.1,0.0);
}
else if (color==indigo){

    Color indigo (0.4,0.2,1.0,0.0);
}
else if (color==ivory){

    Color ivory (0.9,0.9,.0.8,0.0);
}
else if (color==khaki){

    Color khaki (0.8,0.8,0.6,0.0);
}
else if (color==lavender){

    Color lavender (0.6,0.2,0.8,0.0);
}
else if (color==lavenderblush){

    Color lavenderblush (0.8,0.6,0.7,0.0);
}
 else if (color==darkolivegreen){
    Color darkolivegreen (0.4,0.5,0.2,0.0);
  }
else if (color==darkorange){
    Color darkorange (0.9,0.5,0.1,0.0);
  }
else if (color==darkorchid){
    Color darkorchid (0.6,0.2,0.8,0.0);
  }
else if (color==darksalmon){
    Color darksalmon (1.0,0.6,0.5,0.0);
  }
else if (color==darkseagreen){
    Color darkseagreen (0.5,0.7,0.5,0.0);
  }
else if (color==darkslateblue){
    Color darkslateblue (0.2,0.2,0.5,0.0);
  }
else if (color==darkslategray){
    Color darkslategray (0.1,0.3,0.3,0.0);
  }
else if (color==darkturquoise){
    Color darkturquoise (0.2,0.8,0.8,0.0);
  }
else if (color==darkviolet){
    Color darkviolet (0.6,0.1,0.8,0.0);
  }
else if (color==deeppink){
    Color deeppink (1.0,0.1,0.6,0.0);
  }
else if (color==deepskyblue){
    Color deepskyblue (0.0,0.8,1.0,0.0);
  }
else if (color==dimgray){
    Color dimgray (0.8,0.8,0.8,0.0);
  }
else if (color==dimgrey){
    Color dimgrey (0.8,0.8,0.8,0.0);
  }
else if (color==dodgerblue){
    Color dodgerblue (0.0,0.6,1.0,0.0);
  }
else if (color==firebrick) {
    Color firebrick (0.7,0.1,0.0,0.0);
  }
else if (color==floralwhite){
    Color floralwhite (1.0,1.0,0.9,0.0);
  }
  
  //limgreen to navy colors
   else if (color==limegreen){
    Color limegreen (0.2,0.8,0.2,0.0);
  }

 else if (color==linen){
    Color linen (1.0,0.9,0.8,0.0);
  }

 else if (color==magenta){
    Color magenta (1.0,0.0,1.0,0.0);
  }

 else if (color==maroon){
    Color maroon (0.5,0.0,0.0,0.0);
  }

 else if (color==mediumaquamarine){
    Color mediumaquamarine (0.4,0.8,0.7,0.0);
  }

 else if (color==mediumblue){
    Color mediumblue (0.0,0.0,0.8,0.0);
  }

 else if (color==mediumorchid){
    Color mediumorchid (0.7,0.3,0.8,0.0);
  }

 else if (color==mediumpurple){
    Color mediumpurple (0.5,0.4,0.8,0.0);
  }

 else if (color==mediumseagreen){
    Color mediumseagreen (0.2,0.7,0.4,0.0);
  }

 else if (color==mediumslateblue){
    Color mediumslateblue (0.4,0.4,0.9,0.0);
  }

 else if (color==mediumspringgreen){
    Color mediumspringgreen (0.0,0.9,0.6,0.0);
  }

 else if (color==mediumturquoise){
    Color mediumturquoise (0.2,0.8,0.8,0.0);
  }

 else if (color==mediumvioletred){
    Color mediumvioletred (0.7,0.0,0.5,0.0);
  }

 else if (color==midnightblue){
    Color midnightblue (0.0,0.0,0.4,0.0);
  }

 else if (color==mintcream){
    Color mintcream (0.9,1.0,0.9,0.0);
  }

 else if (color==mistyrose){
    Color mistyrose (1.0,0.9,0.9,0.0);
  }

 else if (color==moccasin){
    Color moccasin (1.0,0.9,0.7,0.0);
  }

 else if (color==navajowhite){
    Color navajowhite (1.0,0.8,0.6,0.0);
  }

 else if (color==navy){
    Color navy (0.0,0.0,0.5,0.0);
  }

}
