#include "COLOR.H"
class Colours{
  if(color==black)
  {
    Color Black (0.0,0.0,0.0,0.0);
  }
  else if (color==blue){
    Color Blue (0.0,0.0,0.5,0.0);
  }
  else if (color==cyan){
    Color Cyan (0.0,0.9,0.9,0.0);
  }
  else if (color==darkBlue){
    Color darkBlue (0.1,0,0.4,0.0);
  }
  else if (color==darkCyan){
    Color darkCyan (0.1,0.6,0.8,0.0);
  }
  else if (color==darkGray){
    Color darkGray (0.5,0.5,0.5,0.0);
  }
  else if (color==darkGreen){
    Color darkGreen (0.2,0.3,0.1,0.0);
  }
  else if (color==darkRed){
    Color darkRed (0.5,0.0,0.0,0.0);
  }
  else if (color==darkMagenta){
    Color darkMagenta (0.6,0.0,0.1,0.0);
  }
   else if (color==darkRed){
    Color darkRed (0.7,0.0,0.0,0.0);
  }
   else if (color==darkYellow){
    Color darkYellow (1.0,0.9,0.1,0.0);
  }
  else if (color==gray){
    Color gray (0.5,0.5,0.5,0.0);
  }
  else if (color==green){
    Color green (0.2,0.9,0.0,0.0);
  }
  else if (color==lightGray){
    Color lightGray (0.7,0.7,0.7,0.0);
  }
  else if (color==magenta){
    Color magenta (1.0,0.0,1.0,0.0);
  }
  else if (color==red){
    Color red (1.0,0.0,0.0,0.0);
  }
  else if (color==white){
    Color white (1.0,1.0,1.0,0.0);
  }
  else (color==yellow){
    Color yellow (1.0,1.0,0.1,0.0);
  }
  
  //second section
  else if (color==fuchsia){

    Color fuchsia (255.0,0.0,128.0,0.0);
}
 

   else if (color==forestgreen){

    Color forestgreen (40.0,105.0,3.1,0.0);

}
 else if (color==ghostwhite){

    Color ghostwhite (197.0,205.0,216.0,0.0);

}
 else if (color==gainsboro){

    Color gainsboro(220.0,220.0,220.0,0.0);

}

 else if (color==gold){

    Color gold (253.0,213.0,7.0,0.0);

}

 else if (color==goldenrod){

    Color goldenrod (252.0,214.0,103.0,0.0);

}
else if (color==gray){

    Color gray (192.0,192.0,192.0,0.0);

}
else if (color==green){

    Color green (85.0,212.0,163.0,0.0);

}
else if (color==greenyellow){

    Color greenyellow (153.0,204.0,0.0,0.0);

}

else if (color==grey){

    Color grey (102.0,102.0,102.0,0.0);
}

else if (color==honeydew){

    Color honeydew (242.0,249.0,123.0,0.0);
}
else if (color==hotpink){

    Color hotpink (255.0,0.0,128.0,0.0);
}
else if (color==indianred){

    Color indianred (205.0,92.0,92.0,0.0);
}
else if (color==indigo){

    Color indigo (57.0,100.0,195.0,0.0);
}
else if (color==ivory){

    Color ivory (255.0,255.0,237.0,0.0);
}
else if (color==khaki){

    Color khaki (255.0,244.0,148.0,0.0);
}
else if (color==lavender){

    Color lavender (201.0,146.0,224.0,0.0);
}
else if (color==lavenderblush){

    Color lavenderblush (255.0,240.0,245.0,0.0);
}

}
