#include "COLOR.H"
class Colours{
  if(color==black)
  {
    Color Black (0.0,0.0,0.0,0.0);
  }
  else if (color==blue){
    Color Blue (0.0,0.0,0.5,0.0);
  }
  else if (color==cyan){
    Color Cyan (0.0,0.9,0.9,0.0);
  }
  else if (color==darkBlue){
    Color darkBlue (0.1,0,0.4,0.0);
  }
  else if (color==darkCyan){
    Color darkCyan (0.1,0.6,0.8,0.0);
  }
  else if (color==darkGray){
    Color darkGray (0.5,0.5,0.5,0.0);
  }
  else if (color==darkGreen){
    Color darkGreen (0.2,0.3,0.1,0.0);
  }
  else if (color==darkRed){
    Color darkRed (0.5,0.0,0.0,0.0);
  }
  else if (color==darkMagenta){
    Color darkMagenta (0.6,0.0,0.1,0.0);
  }
}
